development:
  clients:
    default:
      uri: <%= ENV['MONGO_URL'] %>

test:
  clients:
    default:
      uri: <%= ENV['MONGO_URL_TEST'] %>

staging:
  clients:
    default:
      uri: <%= ENV['MONGO_URL'] %>
      options:
        max_pool_size: 16

production:
  clients:
    default:
      uri: <%= ENV['MONGO_URL'] %>
      options:
        max_pool_size: 16
        ssl_ca_cert: ca.pem
