development:
  sessions:
    default:
      uri: <%= ENV['MONGO_URI'] %>
  options:
test:
  sessions:
    default:
      uri: <%= ENV['MONGO_URI'] %>
      options:
        read: primary
        consistency: :strong
        max_retries: 1
        retry_interval: 0
staging:
  sessions:
    default:
      uri: <%= ENV['MONGO_URI'] %>
production:
  sessions:
    default:
      uri: <%= ENV['MONGO_URI'] %>
