# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7e8677324292b632ebcbde127c87a6ba4cf3d513bfa7fda8ce39c4bd5504456d77118ec8225628690771f0539a4278f1ccafc110edec751f14e17684e8aeebc2

test:
  secret_key_base: 66a0cda751d8d21c6b824aa839cd89512be2ccf4b49bb6f8fe3f6ad192382eedc45404d84d1a411c10ae12fee33f5c1d949da719d015cf8dac3eb98addeac4c3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
